/** @format */

import { Geist, Geist_Mono, Kanit } from "next/font/google";
import "./globals.css";

// Import Geist and Geist_Mono fonts
const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

// Import Kanit Medium font
const kanitMedium = Kanit({
	weight: "500", // Medium weight
	variable: "--font-kanit-medium",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={`${geistSans.variable} ${geistMono.variable} ${kanitMedium.variable}`}>{children}</body>
		</html>
	);
}
